### ISSUE TITLE
能否详细写一下如何配置运行

### ISSUE THREAD

**Issue by spinachlover** [senghoo/wordai#12]
运行显示 ImportError: No module named translate.storage.tmx

**Comment by senghoo** [comment]
这个可以试一下([requirements.txt](https://github.com/senghoo/wordai/blob/master/requirements.txt)里已经列出了依赖)：
```
pip install translate-toolkit
```

另外，这个项目属于单纯的技术交流使用。而且README里也写了。这个项目缺乏一些必要的组件：词典、语料库等。因为版权原因这部分不能做公开。基于现有的代码想跑起来，还是需要一定工作量的。
